// imagehive-frontend/src/routes/login/+page.svelte
<script lang="ts">
  import { enhance } from '$app/forms';

  export let form;

  console.log('form', form);
</script>

<form
  use:enhance
  action="/login"
  method="post"
  class="flex w-full max-w-xl flex-col gap-2 self-center"
>
  <h1 class="mb-4 text-2xl font-bold">Login</h1>
  <div class="form-control">
    <label class="label" for="username">
      <span class="label-text">Username</span>
    </label>
    <input class="input input-bordered" name="username" type="text" placeholder="Username" />
  </div>
  <div class="form-control">
    <label class="label" for="password">
      <span class="label-text">Password</span>
    </label>
    <input class="input input-bordered" name="password" type="password" placeholder="Password" />
  </div>

  <button type="submit" class="btn btn-success self-end">Submit</button>
</form>

<style lang="postcss">
</style>

// imagehive-frontend/app/routes/auth/login.tsx
import type {ActionArgs, LoaderArgs} from "@remix-run/node"
import {json} from "@remix-run/node"
import {Form} from "@remix-run/react"
import {Button} from "flowbite-react"
import {authenticator} from "~/services/auth.server"

export async function action({request}: ActionArgs) {
  return await authenticator.authenticate("user-pass", request, {
    successRedirect: "/",
    failureRedirect: "/auth/login",
  })
}

export async function loader({request}: LoaderArgs) {
  const response = await authenticator.isAuthenticated(request, {
    successRedirect: "/",
  })

  return json(response)
}

const Login = () => {
  return (
    <Form
      className="flex flex-col gap-2 max-w-2xl w-full self-center"
      method="post"
    >
      <h1 className="text-3xl font-bold">Login</h1>

      <input type="text" name="username" required />
      <input
        type="password"
        name="password"
        required
        autoComplete="current-password"
      />
      <Button color="grey" type="submit">
        Sign In
      </Button>
    </Form>
  )
}

export default Login
